### ISSUE TITLE
Admin generation script fails due to has and belong to many association

### ISSUE THREAD

**Issue by ankurp** [excid3/madmin#13]
Full stack trace below

```
Skipping ActionMailbox::InboundEmail because database table does not exist
/Users/ankur/.rvm/gems/ruby-3.0.0/gems/activesupport-6.1.1/lib/active_support/inflector/methods.rb:288:in `const_get': uninitialized constant VideoCall::HabtmUsers (NameError)
	from /Users/ankur/.rvm/gems/ruby-3.0.0/gems/activesupport-6.1.1/lib/active_support/inflector/methods.rb:288:in `block in constantize'
	from /Users/ankur/.rvm/gems/ruby-3.0.0/gems/activesupport-6.1.1/lib/active_support/inflector/methods.rb:284:in `each'
	from /Users/ankur/.rvm/gems/ruby-3.0.0/gems/activesupport-6.1.1/lib/active_support/inflector/methods.rb:284:in `inject'
	from /Users/ankur/.rvm/gems/ruby-3.0.0/gems/activesupport-6.1.1/lib/active_support/inflector/methods.rb:284:in `constantize'
	from /Users/ankur/.rvm/gems/ruby-3.0.0/gems/activesupport-6.1.1/lib/active_support/core_ext/string/inflections.rb:74:in `constantize'
	from /Users/ankur/.rvm/gems/ruby-3.0.0/gems/madmin-0.1.1/lib/generators/madmin/resource/resource_generator.rb:85:in `model'
	from /Users/ankur/.rvm/gems/ruby-3.0.0/gems/madmin-0.1.1/lib/generators/madmin/resource/resource_generator.rb:43:in `attributes'
	from /Users/ankur/.rvm/gems/ruby-3.0.0/gems/madmin-0.1.1/lib/generators/madmin/resource/templates/resource.rb.tt:3:in `template'
	from /Users/ankur/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/erb.rb:905:in `eval'
	from /Users/ankur/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/erb.rb:905:in `result'
	from /Users/ankur/.rvm/gems/ruby-3.0.0/gems/thor-1.0.1/lib/thor/actions/file_manipulation.rb:131:in `block in template'
	from /Users/ankur/.rvm/gems/ruby-3.0.0/gems/thor-1.0.1/lib/thor/actions/create_file.rb:53:in `render'
	from /Users/ankur/.rvm/gems/ruby-3.0.0/gems/thor-1.0.1/lib/thor/actions/create_file.rb:63:in `block (2 levels) in invoke!'
	from /Users/ankur/.rvm/gems/ruby-3.0.0/gems/thor-1.0.1/lib/thor/actions/create_file.rb:63:in `open'
	from /Users/ankur/.rvm/gems/ruby-3.0.0/gems/thor-1.0.1/lib/thor/actions/create_file.rb:63:in `block in invoke!'
	from /Users/ankur/.rvm/gems/ruby-3.0.0/gems/thor-1.0.1/lib/thor/actions/empty_directory.rb:117:in `invoke_with_conflict_check'
	from /Users/ankur/.rvm/gems/ruby-3.0.0/gems/thor-1.0.1/lib/thor/actions/create_file.rb:60:in `invoke!'
	from /Users/ankur/.rvm/gems/ruby-3.0.0/gems/thor-1.0.1/lib/thor/actions.rb:93:in `action'
	from /Users/ankur/.rvm/gems/ruby-3.0.0/gems/thor-1.0.1/lib/thor/actions/create_file.rb:25:in `create_file'
	from /Users/ankur/.rvm/gems/ruby-3.0.0/gems/thor-1.0.1/lib/thor/actions/file_manipulation.rb:122:in `template'
	from /Users/ankur/.rvm/gems/ruby-3.0.0/gems/railties-6.1.1/lib/rails/generators/named_base.rb:25:in `block in template'
	from /Users/ankur/.rvm/gems/ruby-3.0.0/gems/railties-6.1.1/lib/rails/generators/named_base.rb:45:in `inside_template'
	from /Users/ankur/.rvm/gems/ruby-3.0.0/gems/railties-6.1.1/lib/rails/generators/named_base.rb:24:in `template'
	from /Users/ankur/.rvm/gems/ruby-3.0.0/gems/madmin-0.1.1/lib/generators/madmin/resource/resource_generator.rb:13:in `generate_resource'
	from /Users/ankur/.rvm/gems/ruby-3.0.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	from /Users/ankur/.rvm/gems/ruby-3.0.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/ankur/.rvm/gems/ruby-3.0.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `block in invoke_all'
	from /Users/ankur/.rvm/gems/ruby-3.0.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `each'
	from /Users/ankur/.rvm/gems/ruby-3.0.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `map'
	from /Users/ankur/.rvm/gems/ruby-3.0.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `invoke_all'
	from /Users/ankur/.rvm/gems/ruby-3.0.0/gems/thor-1.0.1/lib/thor/group.rb:232:in `dispatch'
	from /Users/ankur/.rvm/gems/ruby-3.0.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
	from /Users/ankur/.rvm/gems/ruby-3.0.0/gems/railties-6.1.1/lib/rails/generators.rb:275:in `invoke'
	from /Users/ankur/.rvm/gems/ruby-3.0.0/gems/madmin-0.1.1/lib/madmin/generator_helpers.rb:4:in `call_generator'
	from /Users/ankur/.rvm/gems/ruby-3.0.0/gems/madmin-0.1.1/lib/generators/madmin/install/install_generator.rb:23:in `block in generate_resources'
	from /Users/ankur/.rvm/gems/ruby-3.0.0/gems/madmin-0.1.1/lib/generators/madmin/install/install_generator.rb:21:in `each'
	from /Users/ankur/.rvm/gems/ruby-3.0.0/gems/madmin-0.1.1/lib/generators/madmin/install/install_generator.rb:21:in `generate_resources'
	from /Users/ankur/.rvm/gems/ruby-3.0.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	from /Users/ankur/.rvm/gems/ruby-3.0.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/ankur/.rvm/gems/ruby-3.0.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `block in invoke_all'
	from /Users/ankur/.rvm/gems/ruby-3.0.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `each'
	from /Users/ankur/.rvm/gems/ruby-3.0.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `map'
	from /Users/ankur/.rvm/gems/ruby-3.0.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `invoke_all'
	from /Users/ankur/.rvm/gems/ruby-3.0.0/gems/thor-1.0.1/lib/thor/group.rb:232:in `dispatch'
	from /Users/ankur/.rvm/gems/ruby-3.0.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
	from /Users/ankur/.rvm/gems/ruby-3.0.0/gems/railties-6.1.1/lib/rails/generators.rb:275:in `invoke'
	from /Users/ankur/.rvm/gems/ruby-3.0.0/gems/railties-6.1.1/lib/rails/commands/generate/generate_command.rb:26:in `perform'
	from /Users/ankur/.rvm/gems/ruby-3.0.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	from /Users/ankur/.rvm/gems/ruby-3.0.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/ankur/.rvm/gems/ruby-3.0.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	from /Users/ankur/.rvm/gems/ruby-3.0.0/gems/railties-6.1.1/lib/rails/command/base.rb:69:in `perform'
	from /Users/ankur/.rvm/gems/ruby-3.0.0/gems/railties-6.1.1/lib/rails/command.rb:50:in `invoke'
	from /Users/ankur/.rvm/gems/ruby-3.0.0/gems/railties-6.1.1/lib/rails/commands.rb:18:in `<main>'
	from /Users/ankur/.rvm/gems/ruby-3.0.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /Users/ankur/.rvm/gems/ruby-3.0.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /Users/ankur/.rvm/gems/ruby-3.0.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /Users/ankur/.rvm/gems/ruby-3.0.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /Users/ankur/.rvm/gems/ruby-3.0.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from /Users/ankur/.rvm/gems/ruby-3.0.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
	from /Users/ankur/Projects/OnDemandVideoVisit/bin/rails:5:in `<main>'
	from /Users/ankur/.rvm/gems/ruby-3.0.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
	from /Users/ankur/.rvm/gems/ruby-3.0.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
	from /Users/ankur/.rvm/gems/ruby-3.0.0/gems/spring-2.1.1/lib/spring/commands/rails.rb:6:in `call'
	from /Users/ankur/.rvm/gems/ruby-3.0.0/gems/spring-2.1.1/lib/spring/command_wrapper.rb:38:in `call'
	from /Users/ankur/.rvm/gems/ruby-3.0.0/gems/spring-2.1.1/lib/spring/application.rb:220:in `block in serve'
	from /Users/ankur/.rvm/gems/ruby-3.0.0/gems/activesupport-6.1.1/lib/active_support/fork_tracker.rb:10:in `block in fork'
	from /Users/ankur/.rvm/gems/ruby-3.0.0/gems/activesupport-6.1.1/lib/active_support/fork_tracker.rb:10:in `block in fork'
	from /Users/ankur/.rvm/gems/ruby-3.0.0/gems/activesupport-6.1.1/lib/active_support/fork_tracker.rb:8:in `fork'
	from /Users/ankur/.rvm/gems/ruby-3.0.0/gems/activesupport-6.1.1/lib/active_support/fork_tracker.rb:8:in `fork'
	from /Users/ankur/.rvm/gems/ruby-3.0.0/gems/activesupport-6.1.1/lib/active_support/fork_tracker.rb:26:in `fork'
	from /Users/ankur/.rvm/gems/ruby-3.0.0/gems/activesupport-6.1.1/lib/active_support/fork_tracker.rb:8:in `fork'
	from /Users/ankur/.rvm/gems/ruby-3.0.0/gems/activesupport-6.1.1/lib/active_support/fork_tracker.rb:26:in `fork'
	from /Users/ankur/.rvm/gems/ruby-3.0.0/gems/spring-2.1.1/lib/spring/application.rb:180:in `serve'
	from /Users/ankur/.rvm/gems/ruby-3.0.0/gems/spring-2.1.1/lib/spring/application.rb:145:in `block in run'
	from /Users/ankur/.rvm/gems/ruby-3.0.0/gems/spring-2.1.1/lib/spring/application.rb:139:in `loop'
	from /Users/ankur/.rvm/gems/ruby-3.0.0/gems/spring-2.1.1/lib/spring/application.rb:139:in `run'
	from /Users/ankur/.rvm/gems/ruby-3.0.0/gems/spring-2.1.1/lib/spring/application/boot.rb:19:in `<top (required)>'
	from <internal:/Users/ankur/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/Users/ankur/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from -e:1:in `<main>'
```

**Comment by excid3** [comment]
Can you share the model so we can attempt to reproduce it?

**Comment by ankurp** [comment]
@excid3 I have a repo where I noticed this issue. Code is on GitHub and this is the model https://github.com/ankurp/OnDemandVideoVisit/blob/master/app/models/video_call.rb#L18
I used the jumpstart rails template to create the user model and scaffold the project.

**Comment by excid3** [comment]
Fantastic, thanks! I will get working on that shortly. I imagine we just missed the `has_and_belongs_to_many`, which we can probably treat about the same as a `has_many`

**Comment by excid3** [comment]
Found that the HABTM models are generated dynamically and assigned name here: 
https://github.com/rails/rails/blob/291a3d2ef29a3842d1156ada7526f4ee60dd2b59/activerecord/lib/active_record/associations/builder/has_and_belongs_to_many.rb#L54

Going to use that to skip these models during the installer.
