### ISSUE TITLE
Issue with rails g madmin:install

### ISSUE THREAD

**Issue by mvondoyannick** [excid3/madmin#24]
Have this issue when i run rails g madmin:install command on a fresh rails installation (with MySql DB).

```ruby
rails g madmin:install
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
Running via Spring preloader in process 15459
Traceback (most recent call last):
	42: from -e:1:in `<main>'
	41: from /home/dell/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	40: from /home/dell/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	39: from /home/dell/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
	38: from /home/dell/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
	37: from /home/dell/Bureau/madmin/bin/rails:9:in `<main>'
	36: from /home/dell/.rvm/gems/ruby-2.6.5/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
	35: from /home/dell/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	34: from /home/dell/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	33: from /home/dell/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	32: from /home/dell/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	31: from /home/dell/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	30: from /home/dell/.rvm/gems/ruby-2.6.5/gems/railties-6.0.3.4/lib/rails/commands.rb:18:in `<main>'
	29: from /home/dell/.rvm/gems/ruby-2.6.5/gems/railties-6.0.3.4/lib/rails/command.rb:46:in `invoke'
	28: from /home/dell/.rvm/gems/ruby-2.6.5/gems/railties-6.0.3.4/lib/rails/command/base.rb:69:in `perform'
	27: from /home/dell/.rvm/gems/ruby-2.6.5/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
	26: from /home/dell/.rvm/gems/ruby-2.6.5/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
	25: from /home/dell/.rvm/gems/ruby-2.6.5/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
	24: from /home/dell/.rvm/gems/ruby-2.6.5/gems/railties-6.0.3.4/lib/rails/commands/generate/generate_command.rb:26:in `perform'
	23: from /home/dell/.rvm/gems/ruby-2.6.5/gems/railties-6.0.3.4/lib/rails/generators.rb:276:in `invoke'
	22: from /home/dell/.rvm/gems/ruby-2.6.5/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
	21: from /home/dell/.rvm/gems/ruby-2.6.5/gems/thor-1.1.0/lib/thor/group.rb:232:in `dispatch'
	20: from /home/dell/.rvm/gems/ruby-2.6.5/gems/thor-1.1.0/lib/thor/invocation.rb:134:in `invoke_all'
	19: from /home/dell/.rvm/gems/ruby-2.6.5/gems/thor-1.1.0/lib/thor/invocation.rb:134:in `map'
	18: from /home/dell/.rvm/gems/ruby-2.6.5/gems/thor-1.1.0/lib/thor/invocation.rb:134:in `each'
	17: from /home/dell/.rvm/gems/ruby-2.6.5/gems/thor-1.1.0/lib/thor/invocation.rb:134:in `block in invoke_all'
	16: from /home/dell/.rvm/gems/ruby-2.6.5/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
	15: from /home/dell/.rvm/gems/ruby-2.6.5/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
	14: from /home/dell/.rvm/gems/ruby-2.6.5/gems/madmin-1.0.0/lib/generators/madmin/install/install_generator.rb:11:in `eager_load'
	13: from /home/dell/.rvm/gems/ruby-2.6.5/gems/railties-6.0.3.4/lib/rails/application.rb:507:in `eager_load!'
	12: from /home/dell/.rvm/gems/ruby-2.6.5/gems/railties-6.0.3.4/lib/rails/autoloaders.rb:30:in `each'
	11: from /home/dell/.rvm/gems/ruby-2.6.5/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:393:in `eager_load'
	10: from /home/dell/.rvm/gems/ruby-2.6.5/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:393:in `synchronize'
	 9: from /home/dell/.rvm/gems/ruby-2.6.5/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:404:in `block in eager_load'
	 8: from /home/dell/.rvm/gems/ruby-2.6.5/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:725:in `ls'
	 7: from /home/dell/.rvm/gems/ruby-2.6.5/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:725:in `foreach'
	 6: from /home/dell/.rvm/gems/ruby-2.6.5/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:733:in `block in ls'
	 5: from /home/dell/.rvm/gems/ruby-2.6.5/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:409:in `block (2 levels) in eager_load'
	 4: from /home/dell/.rvm/gems/ruby-2.6.5/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:409:in `const_get'
	 3: from /home/dell/.rvm/gems/ruby-2.6.5/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:26:in `require'
	 2: from /home/dell/.rvm/gems/ruby-2.6.5/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:26:in `tap'
	 1: from /home/dell/.rvm/gems/ruby-2.6.5/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:27:in `block in require'
/home/dell/.rvm/gems/ruby-2.6.5/gems/zeitwerk-2.4.2/lib/zeitwerk/loader/callbacks.rb:18:in `on_file_autoloaded': expected file /home/dell/Bureau/madmin/app/madmin/resources/action_text/rich_text_resource.rb to define constant ActionText::RichTextResource, but didn't (Zeitwerk::NameError)
```
Solution:

To resolv this issue, you have to read this link about Zeitwerk
https://stackoverflow.com/questions/57277351/rails-6-zeitwerknameerror-doesnt-load-class-from-module

**Comment by fiveNinePlusR** [comment]
That's odd. worked fine for me on a brand new rails 6.1.1 install. perhaps prepend DISABLE_SPRING=1 to the command and try it again? 

Alternatively, does running it with `bundle exec` work? I know rvm does some funky stuff so it also can get in the way.

**Comment by excid3** [comment]
You'll have to share the contents of `app/madmin/resources/action_text/rich_text_resource.rb` when that error occurs.

It's been working fine for me and several other people with ActionText, so not sure.
